--CREATE DATABASE LSD1
USE LSD1;
CREATE TABLE LIKES1 (
LIKER1 VARCHAR(30) NOT NULL,
LIKED1 VARCHAR(30) NOT NULL);

CREATE TABLE LIKES2 (
LIKER2 VARCHAR(30) NOT NULL,
LIKED2 VARCHAR(30) NOT NULL);

CREATE VIEW DUOS(USER1,USER2) AS
SELECT LIKER1,LIKER2
FROM LIKES1,LIKES2 
WHERE LIKER1=LIKED2 AND LIKER2=LIKED1 



DROP VIEW DUOS 